config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :organizations do
    scope module: 'organizations' do
      resources :projects
      resources :logs, only: %i[index]
      resources :webhooks, only: %i[index]
      resources :confirmations, only: %i[create]
    end
  end

  resources :projects, only: [], shallow: true do
    scope module: 'projects' do
      resources :integrations
    end
  end

  resources :integrations, only: [], shallow: true do
    scope module: 'integrations' do
      resources :confirmations, only: %i[create]
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      namespace :webhooks do
        resources :logs, only: %i[create]
      end
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'organizations#index'
end

app/models/organization.rb
# frozen_string_literal: true

class Organization
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  validates :name, presence: true, uniqueness: true

  field :origin, type: String

  field :origin_confirmed_at, type: Time
  field :public_secret, type: String

  field :sent_last_webhook_at, type: Time

  field :webhook_events, type: Hash, default: {
    logs: {
      create: true
    },
    projects: {
      create: true,
      update: true,
      destroy: true
    },
    integrations: {
      create: true,
      update: true,
      destroy: true
    }
  }

  with_options dependent: :delete_all do
    has_many :projects
    has_many :outbound_webhook
  end
end

app/models/project.rb
# frozen_string_literal: true

class Project
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  validates :name, presence: true, uniqueness: { scope: :organization_id }

  belongs_to :organization

  has_many :integrations, dependent: :delete_all
end

app/controllers/organizations/confirmations_controller.rb
# frozen_string_literal: true

module Organizations
  class ConfirmationsController < ApplicationController
    before_action :set_organization

    def create
      parts_of_url = URI.split(@organization.origin)

      begin
        url = URI::Generic.build(parts_of_url).to_s.freeze
      rescue ArgumentError, InvalidComponentError => e
        warn(e.message, e.class, uplevel: 1)

        flash[:notice] = e.message

        redirect_back(fallback_location: @organization)
      else
        uri = URI(url)
        Net::HTTP.start(uri.host) do |http|
          http.read_timeout = 5

          request = Net::HTTP::Get.new(uri)
          request.content_type = 'application/json'
          request['Accept'] = 'application/json'
          request['User-Agent'] = 'rails_webhook_system/1.0'
          code = http.request(request).code.to_i

          if code == 200
            @organization.update!(origin_confirmed_at: Time.current, public_secret: SecureRandom.base58(24))

            flash[:notice] = 'Organization was successfully confirmed.'
          end

          redirect_back(fallback_location: @organization)
        end
      end
    end

    private

    def set_organization
      @organization = Organization.find(params.require(:organization_id))
    end
  end
end

app/controllers/organizations/logs_controller.rb
# frozen_string_literal: true

module Organizations
  class LogsController < ApplicationController
    def index
      @logs = Log.where(organization:).desc(:created_at)
    end

    private

    def organization
      @organization ||= Organization.find(params.require(:organization_id))
    end
  end
end

app/controllers/organizations/projects_controller.rb
# frozen_string_literal: true

module Organizations
  class ProjectsController < ApplicationController
    before_action :set_organization
    before_action :set_project, only: %i[show edit update destroy]

    def index
      @projects = Project.where(organization: @organization)
    end

    def show; end

    def new
      @project = Project.new(organization: @organization)
    end

    def edit; end

    def create
      @project = Project.new(project_params)
      @project.organization = @organization

      if @project.save
        OutboundWebhookJob.perform_now(@project.organization.id.to_s, @project.attributes, controller_name, action_name)
        redirect_to organization_project_path(@organization, @project), notice: 'Project was successfully created.'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @project.update(project_params)
        OutboundWebhookJob.perform_now(@project.organization.id.to_s, @project.attributes, controller_name, action_name)
        redirect_to organization_project_path(@organization, @project), notice: 'Project was successfully updated.',
                                                                        status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @project.destroy!
      OutboundWebhookJob.perform_now(@project.organization.id.to_s, @project.attributes, controller_name, action_name)
      redirect_to organization_projects_path(@organization), notice: 'Project was successfully destroyed.',
                                                             status: :see_other
    end

    private

    def set_organization
      @organization = Organization.find(params.require(:organization_id))
    end

    def set_project
      @project = Project.where(organization: @organization).find(params.require(:id))
    end

    def project_params
      params.require(:project).permit(:name)
    end
  end
end

app/controllers/organizations/webhooks_controller.rb
# frozen_string_literal: true

module Organizations
  class WebhooksController < ApplicationController
    def index
      @outbound_webhooks = OutboundWebhook.where(organization:).desc(:created_at)
    end

    private

    def organization
      @organization ||= Organization.find(params.require(:organization_id))
    end
  end
end

app/controllers/organizations_controller.rb
# frozen_string_literal: true

class OrganizationsController < ApplicationController
  before_action :set_organization, only: %i[show edit update destroy]

  def index
    @organizations = Organization.all
  end

  def show; end

  def new
    @organization = Organization.new
  end

  def edit; end

  def create
    @organization = Organization.new(organization_params)

    if @organization.save
      redirect_to @organization, notice: 'Organization was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @organization.update(organization_params)
      redirect_to @organization, notice: 'Organization was successfully updated.', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @organization.destroy!
    redirect_to organizations_url, notice: 'Organization was successfully destroyed.', status: :see_other
  end

  private

  def set_organization
    @organization = Organization.find(params.require(:id))
  end

  def organization_params
    params.require(:organization).permit(:name, :origin, webhook_events: {})
  end
end

app/controllers/projects/integrations_controller.rb
# frozen_string_literal: true

module Projects
  class IntegrationsController < ApplicationController
    before_action :set_project, only: %i[index show new edit create update]
    before_action :set_integration, only: %i[show edit update]

    def index
      @integrations = Integration.where(project: @project)
    end

    def show; end

    def new
      @integration = Integration.new(project: @project)
    end

    def edit; end

    def create
      @integration = Integration.new(integration_params)
      @integration.project = @project
      @integration.organization = @project.organization

      if @integration.save
        OutboundWebhookJob.perform_now(@integration.organization.id.to_s, @integration.attributes, controller_name,
                                       action_name)
        redirect_to organization_project_path(@project.organization, @project),
                    notice: 'Integration was successfully created.'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @integration.update(integration_params)
        OutboundWebhookJob.perform_now(@integration.organization.id.to_s, @integration.attributes, controller_name,
                                       action_name)
        redirect_to project_project_path(@integration, @integration), notice: 'Integration was successfully updated.',
                                                                      status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      integration = Integration.find(params.require(:id))
      OutboundWebhookJob.perform_now(integration.organization.id.to_s, integration.attributes, controller_name,
                                     action_name)
      integration.destroy!
      redirect_back(
        fallback_location: organization_project_path(integration.project),
        notice: 'Integration was successfully destroyed.',
        status: :see_other
      )
    end

    private

    def set_project
      @project = Project.find(params.require(:project_id))
    end

    def set_integration
      @integration = Integration.where(project: @project).find(params.require(:id))
    end

    def integration_params
      params.require(:integration).permit(:name, :origin)
    end
  end
end

app/views/organizations/projects/_form.html.slim
= form_with(model: [@organization, project]) do |form|
  - if project.errors.any?
    h2
      | "#{pluralize(project.errors.count, 'error')} prohibited this project from being saved:
    ul
      - project.errors.each do |error|
        li
          = error.full_message

  div
    = form.label :name
    = form.text_field :name

  = form.submit

app/views/organizations/projects/_project.html.slim
article
  nav
    ul
      li
        strong
          =< project.name
    ul
      li
        = link_to '→', organization_project_path(@organization, project), title: 'Show this project'

app/views/organizations/projects/edit.html.slim
nav[aria-label='breadcrumb']
  ul
    li
      = link_to 'Projects', organization_projects_path(@organization), title: 'Back to projects'
    li
      = link_to @project.name, organization_project_path(@organization, @project), title: 'Show this project'
    li
      | Editing project

= render 'form', project: @project

app/views/organizations/projects/index.html.slim
nav
  ul
    li
      | Projects
  ul
    li
      = link_to 'New project', new_organization_project_path(@organization)

= render @projects

app/views/organizations/projects/new.html.slim
nav[aria-label='breadcrumb']
  ul
    li
      = link_to 'Projects', organization_projects_path(@organization), title: 'Back to projects'
    li
      | New project

= render 'form', project: @project

app/views/organizations/projects/show.html.slim
nav[aria-label='breadcrumb']
  ul
    li
      = link_to 'Projects', organization_projects_path(@organization), title: 'Back to projects'
    li
      = @project.name

article
  header
    nav
      ul
        li
          strong
            | Name:
          =< @project.name
      ul
        li
          = link_to 'Edit this project', edit_organization_project_path(@organization, @project)
  small
    strong
      | Created at:
    =< human_date(@project.created_at)

= button_to 'Destroy this project', organization_project_path(@organization, @project), method: :delete, data: { turbo_confirm: 'Are you sure?' }

nav
  ul
    li
      | Integrations
  ul
    li
      = link_to 'New integrations', new_project_integration_path(@project)
hr
aside
  nav
    ul
      - @project.integrations.each do |integration|
        li
          details
            summary
              strong
                = integration.name
              br
              small
                u
                  = integration.origin
              - if integration.confirmed_at?
                ins
                  sup
                    |< +
              - else
                sub
                  |< -
            article
              header
                strong
                  = integration.public_secret
              - integration.logs.each do |log|
                blockquote
                  = log.body
                  footer
                    cite
                      = human_date(log.created_at)
              footer
                - unless integration.confirmed_at?
                  = button_to 'Confirm this integration', integration_confirmations_path(integration), method: :post
                = button_to 'Destroy this integration', integration, method: :delete, data: { turbo_confirm: 'Are you sure?' }