config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :organizations do
    scope module: 'organizations' do
      resources :projects
      resources :logs, only: %i[index]
      resources :webhooks, only: %i[index]
      resources :confirmations, only: %i[create]
    end
  end

  resources :projects, only: [], shallow: true do
    scope module: 'projects' do
      resources :integrations
    end
  end

  resources :integrations, only: [], shallow: true do
    scope module: 'integrations' do
      resources :confirmations, only: %i[create]
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      namespace :webhooks do
        resources :logs, only: %i[create]
      end
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'organizations#index'
end

app/models/organization.rb
# frozen_string_literal: true

class Organization
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  validates :name, presence: true, uniqueness: true

  field :origin, type: String

  field :origin_confirmed_at, type: Time
  field :public_secret, type: String

  field :sent_last_webhook_at, type: Time

  field :webhook_events, type: Hash, default: {
    logs: {
      create: true
    },
    projects: {
      create: true,
      update: true,
      destroy: true
    },
    integrations: {
      create: true,
      update: true,
      destroy: true
    }
  }

  with_options dependent: :delete_all do
    has_many :projects
    has_many :outbound_webhook
  end
end

app/controllers/organizations/confirmations_controller.rb
# frozen_string_literal: true

module Organizations
  class ConfirmationsController < ApplicationController
    before_action :set_organization

    def create
      parts_of_url = URI.split(@organization.origin)

      begin
        url = URI::Generic.build(parts_of_url).to_s.freeze
      rescue ArgumentError, InvalidComponentError => e
        warn(e.message, e.class, uplevel: 1)

        flash[:notice] = e.message

        redirect_back(fallback_location: @organization)
      else
        uri = URI(url)
        Net::HTTP.start(uri.host) do |http|
          http.read_timeout = 5

          request = Net::HTTP::Get.new(uri)
          request.content_type = 'application/json'
          request['Accept'] = 'application/json'
          request['User-Agent'] = 'rails_webhook_system/1.0'
          code = http.request(request).code.to_i

          if code == 200
            @organization.update!(origin_confirmed_at: Time.current, public_secret: SecureRandom.base58(24))

            flash[:notice] = 'Organization was successfully confirmed.'
          end

          redirect_back(fallback_location: @organization)
        end
      end
    end

    private

    def set_organization
      @organization = Organization.find(params.require(:organization_id))
    end
  end
end

app/controllers/organizations/logs_controller.rb
# frozen_string_literal: true

module Organizations
  class LogsController < ApplicationController
    def index
      @logs = Log.where(organization:).desc(:created_at)
    end

    private

    def organization
      @organization ||= Organization.find(params.require(:organization_id))
    end
  end
end

app/controllers/organizations/projects_controller.rb
# frozen_string_literal: true

module Organizations
  class ProjectsController < ApplicationController
    before_action :set_organization
    before_action :set_project, only: %i[show edit update destroy]

    def index
      @projects = Project.where(organization: @organization)
    end

    def show; end

    def new
      @project = Project.new(organization: @organization)
    end

    def edit; end

    def create
      @project = Project.new(project_params)
      @project.organization = @organization

      if @project.save
        OutboundWebhookJob.perform_now(@project.organization.id.to_s, @project.attributes, controller_name, action_name)
        redirect_to organization_project_path(@organization, @project), notice: 'Project was successfully created.'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @project.update(project_params)
        OutboundWebhookJob.perform_now(@project.organization.id.to_s, @project.attributes, controller_name, action_name)
        redirect_to organization_project_path(@organization, @project), notice: 'Project was successfully updated.',
                                                                        status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @project.destroy!
      OutboundWebhookJob.perform_now(@project.organization.id.to_s, @project.attributes, controller_name, action_name)
      redirect_to organization_projects_path(@organization), notice: 'Project was successfully destroyed.',
                                                             status: :see_other
    end

    private

    def set_organization
      @organization = Organization.find(params.require(:organization_id))
    end

    def set_project
      @project = Project.where(organization: @organization).find(params.require(:id))
    end

    def project_params
      params.require(:project).permit(:name)
    end
  end
end

app/controllers/organizations/webhooks_controller.rb
# frozen_string_literal: true

module Organizations
  class WebhooksController < ApplicationController
    def index
      @outbound_webhooks = OutboundWebhook.where(organization:).desc(:created_at)
    end

    private

    def organization
      @organization ||= Organization.find(params.require(:organization_id))
    end
  end
end

app/controllers/organizations_controller.rb
# frozen_string_literal: true

class OrganizationsController < ApplicationController
  before_action :set_organization, only: %i[show edit update destroy]

  def index
    @organizations = Organization.all
  end

  def show; end

  def new
    @organization = Organization.new
  end

  def edit; end

  def create
    @organization = Organization.new(organization_params)

    if @organization.save
      redirect_to @organization, notice: 'Organization was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @organization.update(organization_params)
      redirect_to @organization, notice: 'Organization was successfully updated.', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @organization.destroy!
    redirect_to organizations_url, notice: 'Organization was successfully destroyed.', status: :see_other
  end

  private

  def set_organization
    @organization = Organization.find(params.require(:id))
  end

  def organization_params
    params.require(:organization).permit(:name, :origin, webhook_events: {})
  end
end

app/views/organizations/_form.html.slim
= form_with(model: organization) do |form|
  - if organization.errors.any?
    h2
      | #{pluralize(organization.errors.count, 'error')} prohibited this organization from being saved:
    ul
      - organization.errors.each do |error|
        li
          = error.full_message

  div
    = form.label :name
    = form.text_field :name

  div
    = form.label :origin
    = form.url_field :origin

  article
    - form.object.class.new.webhook_events.each do |name, value|
      strong
        = name
      div
        - value.each do |nested_name, nested_value|
          - input_name = "#{form.object_name}[webhook_events][#{name}][#{nested_name}]"
          = check_box_tag input_name, true, form.object.webhook_events.fetch(name.to_s, {}).fetch(nested_name.to_s, false)
          = label_tag input_name, nested_name

  = form.submit

app/views/organizations/_organization.html.slim
article
  nav
    ul
      li
        strong
          =< organization.name
    ul
      li
        = link_to '→', organization, title: 'Show this organization'

app/views/organizations/edit.html.slim
nav[aria-label='breadcrumb']
  ul
    li
      = link_to 'Organizations', organizations_path, title: 'Back to organizations'
    li
      = link_to @organization.name, @organization, title: 'Show this organization'
    li
      | Editing organization

= render 'form', organization: @organization

app/views/organizations/index.html.slim
nav
  ul
    li
      | Organizations
  ul
    li
      = link_to 'New organization', new_organization_path

= render @organizations

app/views/organizations/new.html.slim
nav[aria-label='breadcrumb']
  ul
    li
      = link_to 'Organizations', organizations_path, title: 'Back to organizations'
    li
      | New organization

= render 'form', organization: @organization

app/views/organizations/show.html.slim
nav[aria-label='breadcrumb']
  ul
    li
      = link_to 'Organizations', organizations_path, title: 'Back to organizations'
    li
      = @organization.name

article
  header
    nav
      ul
        li
          strong
            | Name:
          =< @organization.name
      ul
        li
          = link_to 'Edit this organization', edit_organization_path(@organization)
  nav
    ul
      li
        strong
          | Projects
    ul
      li
        = link_to '→', organization_projects_path(@organization), title: 'View projects'
  nav
    ul
      li
        strong
          | Logs
    ul
      li
        = link_to '→', organization_logs_path(@organization), title: 'View projects'
  nav
    ul
      li
        strong
          | Webhooks
    ul
      li
        = link_to '→', organization_webhooks_path(@organization), title: 'View webhooks'
  footer
    small
      strong
        | Created at:
      =< human_date(@organization.created_at)
    - if @organization.origin?
      br
      u
        = @organization.origin
      - if @organization.origin_confirmed_at?
        ins
          sup
            |< +
      - else
        sub
          |< -
      - if @organization.origin_confirmed_at?
        br
        strong
          = @organization.public_secret
      - else
        = button_to 'Confirm this Organization', organization_confirmations_path(@organization), method: :post

= button_to 'Destroy this organization', organization_path(@organization), method: :delete, data: { turbo_confirm: 'Are you sure?' }